### ISSUE TITLE
Can or should I run signalmaster over ssl ?

### ISSUE THREAD

**Issue by Rapy** [andyet/signalmaster#10]
Question:

Can or should I run signalmaster over ssl ?

Would it be sufficient to just adapt the socket.io to https?

**Comment by DadaMonad** [comment]
The client does not communicate much with the signaling server. So you definitely won't experience any performance problems if you use https. I was required for my website, because it is served via https only and chrome complains that you have "Mixed Content" if you access the signaling server via http. Therefore, I added support for https and created a pull request (check my repository if it is not accepted yet).
