### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by marke123** [andyet/signalmaster#83]
Hi, I'm using your SignalMaster server, the latest from Github, and I'm using your latest SimpleWebRTC - the simplewebrtc.bundle.js - also the latest from Github. 

I have a simple audio chat demo set up, similar to the audio demo at simplewebrtc.com (very helpful demo, thanks!). 

In the client side JS code in the call to "new SimpleWebRTC( { ... } ) I have a url parameter set to point to my SignalMaster server. When I load up the client it sends a GET request like this:

`https://XXXXXXXXXX:9002/socket.io/1/?t=1460762455383`

The response comes back as a "400 - Bad Request" and this response body:  

`{"code":0,"message":"Transport unknown"}`

The SignalMaster server is using node module socket.io 1.3.7, and the client is using the client lib of socket.io-1.4.5.js

Any idea why, or how to resolve this issue?  Or should I post this over in your SimpleWebRTC repo instead?

**Comment by marke123** [comment]
I figured this out, you can close the issue. Thanks!

**Comment by Wasser-Eis** [comment]
I have the same error.
Please explain how you fixed it.

**Comment by fippo** [comment]
most likely a version conflict between socket.io versions. I'd recommend going for 1.3.7 on both sides.

**Comment by vinodmap** [comment]
I'm not sure this will get any attention since this issue is already closed, if no response, I can open a new issue.  I installed signalmaster on a remote AWS server.  From my Mac using Chrome, I went to http://35.xxx.xxx.xxx:8888/socket.io/  and I get the result:

> {"code":0,"message":"Transport unknown"}

From my Windows machine (also using Chrome), I do the same thing (go to http://35.xxx.xxx.xxx:8888/socket.io/) and I get 404 Not Found error.

I checked that on the server, the signalmaster that is running is using socket.io 1.3.7.  On the client, I am not running my own copy of simplwebrtc.  For now, just pointing to  <script src="https://simplewebrtc.com/latest-v2.js">.  Will that automatically pick up the latest updates to https://github.com/andyet/SimpleWebRTC, which uses socket.io 1.3.7 ?  How else can I resolve this?  Thanks.
